name: Flatpak

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flatpak
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder
          export XDG_RUNTIME_DIR=/tmp/xdg-runtime-$UID
          mkdir -p "$XDG_RUNTIME_DIR"
          chmod 700 "$XDG_RUNTIME_DIR"
          flatpak --user remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          flatpak --user remote-add --if-not-exists flathub-beta https://dl.flathub.org/beta-repo/flathub-beta.flatpakrepo

      - name: Build Flatpak
        run: |
          export XDG_RUNTIME_DIR=/tmp/xdg-runtime-$UID
          mkdir -p "$XDG_RUNTIME_DIR"
          chmod 700 "$XDG_RUNTIME_DIR"
          flatpak-builder --user --repo=flatpak-repo --install-deps-from=flathub --install-deps-from=flathub-beta --force-clean --disable-rofiles-fuse build-dir build-aux/flatpak/dev.rotstein.SmashedPumpkin.json

      - name: Bundle Flatpak
        run: |
          flatpak build-bundle --arch=x86_64 flatpak-repo SmashedPumpkin.flatpak dev.rotstein.SmashedPumpkin master

      - name: Upload Bundle
        uses: actions/upload-artifact@v4
        with:
          name: SmashedPumpkin.flatpak
          path: SmashedPumpkin.flatpak
